package org.example.selenoid;


import java.util.Objects;

/**
 * This class is for managing the url of logs generated by selenoid.
 * <p>
 * 2023/9/1
 * @author Yong Yang
 * @version 1.0
 * @since 1.0
 */
public final class LogUrlManager {
    private LogUrlManager() {

    }
    private static final ThreadLocal<String> logUrl = new ThreadLocal<>();
    public static void set(String logUrl) {
        if (Objects.nonNull(logUrl))
            LogUrlManager.logUrl.set(logUrl);
    }

    public static String get() {
        return logUrl.get();
    }

    public static void remove() {
        logUrl.remove();
    }
}
