package org.example.selenoid;

import java.util.Objects;

/**
 * This class is for managing the url of videos generated by selenoid.
 * <p>
* 2023/9/1
* @author Yong Yang
* @version 1.0
* @since 1.0
*/
public final class VideoUrlManager {
    private VideoUrlManager() {

    }

    private static final ThreadLocal<String> videoUrl = new ThreadLocal<>();
    public static void set(String videoUrl) {
        if (Objects.nonNull(videoUrl))
            VideoUrlManager.videoUrl.set(videoUrl);
    }

    public static String get() {
        return videoUrl.get();
    }

    public static void remove() {
        videoUrl.remove();
    }
}
